import React, { useState } from "react";
import "./SqlPanel.css";

interface SqlPanelProps {
  sql: string | null;
}

const SqlPanel: React.FC<SqlPanelProps> = ({ sql }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (sql) {
      navigator.clipboard.writeText(sql);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const formatSql = (sqlString: string): string => {
    // Basic SQL formatting - add line breaks after keywords
    return sqlString
      .replace(/\bSELECT\b/gi, '\nSELECT')
      .replace(/\bFROM\b/gi, '\nFROM')
      .replace(/\bWHERE\b/gi, '\nWHERE')
      .replace(/\bAND\b/gi, '\n  AND')
      .replace(/\bOR\b/gi, '\n  OR')
      .replace(/\bGROUP BY\b/gi, '\nGROUP BY')
      .replace(/\bORDER BY\b/gi, '\nORDER BY')
      .replace(/\bHAVING\b/gi, '\nHAVING')
      .replace(/\bJOIN\b/gi, '\nJOIN')
      .replace(/\bLEFT JOIN\b/gi, '\nLEFT JOIN')
      .replace(/\bRIGHT JOIN\b/gi, '\nRIGHT JOIN')
      .replace(/\bINNER JOIN\b/gi, '\nINNER JOIN')
      .replace(/\bON\b/gi, '\n  ON')
      .replace(/\bUNION\b/gi, '\nUNION')
      .trim();
  };

  return (
    <div className="sql-panel-container">
      {sql && (
        <div className="sql-panel-toolbar">
          <button className="copy-btn" onClick={handleCopy} title="Copy SQL">
            {copied ? (
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="20 6 9 17 4 12" />
              </svg>
            ) : (
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
              </svg>
            )}
            <span>{copied ? "Copied!" : "Copy"}</span>
          </button>
        </div>
      )}

      <div className="sql-content">
        {sql ? (
          <pre className="sql-code">
            <code>{formatSql(sql)}</code>
          </pre>
        ) : (
          <div className="sql-empty">
            <div className="empty-icon">
              <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                <path d="M4 7V4h16v3" />
                <path d="M9 20h6" />
                <path d="M12 4v16" />
              </svg>
            </div>
            <p className="empty-title">No SQL Generated</p>
            <p className="empty-subtitle">SQL queries will appear here when agents retrieve data</p>
          </div>
        )}
      </div>

      {sql && (
        <div className="sql-footer">
          <div className="sql-info">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="10" />
              <path d="M12 16v-4" />
              <path d="M12 8h.01" />
            </svg>
            <span>Auto-generated by KPI Gateway Agent</span>
          </div>
        </div>
      )}
    </div>
  );
};

export default SqlPanel;
